// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAhN2ydjc-X28wGu_GISHFBfsbPEqzmY6k',
//     appId: '1:938301732033:web:b892d89a2974f8a53ad040',
//     messagingSenderId: '938301732033',
//     projectId: 'expensia-c2f5b',
//     authDomain: 'expensia-c2f5b.firebaseapp.com',
//     storageBucket: 'expensia-c2f5b.firebasestorage.app',
//     measurementId: 'G-FXM2WM49HZ',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCHAHlyne9I4riJJEYsF8ksqchN7njIo3A',
//     appId: '1:938301732033:android:155497882e8a7c6e3ad040',
//     messagingSenderId: '938301732033',
//     projectId: 'expensia-c2f5b',
//     storageBucket: 'expensia-c2f5b.firebasestorage.app',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBLwE9EqxXfUg7cWzDqperckAkwXoSAf2A',
//     appId: '1:938301732033:ios:42ff2bd17c3bf9ec3ad040',
//     messagingSenderId: '938301732033',
//     projectId: 'expensia-c2f5b',
//     storageBucket: 'expensia-c2f5b.firebasestorage.app',
//     iosBundleId: 'com.expensia.app',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBLwE9EqxXfUg7cWzDqperckAkwXoSAf2A',
//     appId: '1:938301732033:ios:f89b6017bfafabdc3ad040',
//     messagingSenderId: '938301732033',
//     projectId: 'expensia-c2f5b',
//     storageBucket: 'expensia-c2f5b.firebasestorage.app',
//     iosBundleId: 'com.example.expensia',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAhN2ydjc-X28wGu_GISHFBfsbPEqzmY6k',
//     appId: '1:938301732033:web:6cc7e8e79022917d3ad040',
//     messagingSenderId: '938301732033',
//     projectId: 'expensia-c2f5b',
//     authDomain: 'expensia-c2f5b.firebaseapp.com',
//     storageBucket: 'expensia-c2f5b.firebasestorage.app',
//     measurementId: 'G-0Y9Z17WXNR',
//   );
// }
